### ISSUE TITLE
Less efficient code.

### ISSUE THREAD

**Issue by abhinav0000** [HarkiratSingh7/OSBasicAlgos#1]
As I was going through your code I saw a minute thing but It creates a huge difference when it to comes to the efficiency of writing a code.
I would like to suggest you to use
"using namespace std;"  before #include 
so you don't need to write in every single line of code.
and you can also add #include<bits/stdc++.h> as it includes all the header files you need.

**Comment by HarkiratSingh7** [comment]
Yes I do agree. But the thing is 'using namedpace std' in a library headers can actually sometimes create complications when those headers are included in the source files.

I have always used the 'using namespace' in source files (where I see it doesn't create unnecessary errors).

For example, if something is defined in a std namedpace, and the same is defined in my header, the compiler would have to do a lot in order to resolve it. Sometimes it would fail to resolve properly.
That's why I don't use std in library header files.
It actually makes less efficient code, and can result in huge amount of errors which is a nightmare for a programmer.

I would advise you to limit the use of 'using namedpace' directive, and use it only where you are sure that your custom defined tokens don't interfere with those in the std lib, so that compiler can avoid producing unnecessary errors. (Note sometimes the compiler can actually distinguish between the same name definitions, but not always).

**Comment by HarkiratSingh7** [comment]
Secondly, many compilers don't support bits/stdc++.h header.
I know that gcc and mingw support that.

And actually when the c++ compiler would parse the file, it would move everything from the bits/stdc++.h file and concatenate with my sources (during its analysis and compilation phase)
It would include so much unnecessary stuff that it would tremendously increase the compilation time. 

So the good practice is to include only that, which the code requires.
